config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  post 'posts/create', to: "posts#create", as: "post_create"
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true
    validates :image, presence: true
    before_save :ban_word
    def ban_word
        self.content.gsub!("spoiler"," ")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order('created_at DESC')
  end


  def create
    @post = Post.create(
      title: params['title'],
      content: params['content'],
      image: params['image']
    )
    # @post.content.gsub!("spoiler"," ")
    if @post.save
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<% if @post.present? && @post.errors.any? %>  
    <div id="error_explanation"> 
        <h2>
            <%= pluralize(@post.errors.count, "error") %>
            prohibited this post from being saved:
        </h2>
        <ul>
            <% @post.errors.full_messages.each do |msg|%>
                <li><%= msg %> </li>
            <% end%>
        </ul>
    </div>
<% end %>

app/views/posts/index.html.erb
<% if @post.present? && @post.errors.any? %>
    <div id="error_explanation"> 
        <h2>
            <%= pluralize(@post.errors.count, "error") %>
            prohibited this post from being saved:
        </h2>
        <ul>
            <% @post.errors.full_messages.each do |msg|%>
                <li><%= msg %> </li>
            <% end%>
        </ul>
    </div>©
<%end%>

<h1> TODOS LOS POSTS </h1>

<div class="container mt-5 mb-5">
  <%= form_with(url: post_create_path, model:@post, local:true) do |f|%>
    <%= f.label :titulo%>
    <%= f.text_field :title%>

    <%= f.label :image%>
    <%= f.text_field :image%>

    <%= f.label :contenido%>
    <%= f.text_field :content%>

    <%= f.submit "Creat post"%>
    
  <%end%>
</div>
<% @posts.each do |post| %>
<div class="card mb-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <%= image_tag post.image, class:"img-fluid"%>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"> <%= post.title %></h5>
        <p class="card-text"> <%= post.content %></p>
        <p class="card-text"><small class="text-muted"><%= post.created_at %></small></p>
      </div>
    </div>
  </div>
</div>



<% end %>